### ISSUE TITLE
Chart labels on the dashboard not displaying properly

### ISSUE THREAD

**Issue by lharv076** [opennorth/citizenbudgetapp.com#125] opened 2016-05-16 15:03 UTC
When a question has too many options to choose from, the chart on the dashboard shows all these options overlapping. (see screenshot attached). I would usually be able to add this code snippet to fit the way the chart is displayed, but it is not working anymore. 

**Code:**
# graph_57290f53a7ceae57ad0000e3 svg {

  height: 500px !important;
}
# graph_57290f53a7ceae57ad0000e3 g.x.axis text {

  -webkit-transform: rotate(-45deg);
  -ms-transform: rotate(-45deg);
  transform: rotate(-45deg);
  font-size: 80%;
  text-anchor: end !important;
}

This could have something to do with fixing the AODA sliders when the answers weren't being recorded. 

Can you take a look and let me know how I can modify this code to rotate all the option labels in the chart so that they're displayed better?

Here is the questionnaire's [back-end](http://ca1.opennorth.ca/admin/questionnaires/5729056da7ceae57ad0000c0) (they are live currently - be careful!) and here is the live [consultation](http://saskatoon.citizenbudget.com/). It's for the "neighbourhood" question in the demographics section.

**Comment by gmattar** [comment] 2016-05-16 19:29
@lharv076, you forgot to attach the screenshot. Is this happening on the response page (after user's submission) or on the summary (admin environment)?

**Comment by lharv076** [comment] 2016-05-16 19:33
<img width="780" alt="dashboardchartproblem" src="https://cloud.githubusercontent.com/assets/13963466/15301329/3cdb637e-1b7b-11e6-8156-a9350fe85ec5.png">

Here is the screenshot, sorry about that. It's happening on the admin environment. The demographics question's answers don't appear on the user results page (on purpose).

**Comment by gmattar** [comment] 2016-05-16 20:21
The admin pages don't import custom CSS/JS, so that code won't work in this case. It will on the response page, though.

**Comment by lharv076** [comment] 2016-05-16 20:31
Hm, is there anything we can do to fix it on the admin pages?

**Comment by gmattar** [comment] 2016-05-17 00:31
I tried to enable the custom CSS on the admin area and it broke a lot of things. After that, I set the styles you want as default, but it still looks bad.

![screenshot from 2016-05-16 21-22-58](https://cloud.githubusercontent.com/assets/1631275/15307829/4c5ef1a8-1bad-11e6-9ac3-22c67bac4e93.png)

**Comment by lharv076** [comment] 2016-05-17 12:47
Ah OK I see.

We'll just leave it then! Thank you for looking into it for me :)

On Mon, May 16, 2016 at 8:31 PM, Guilherme Mattar Bastos <
notifications@github.com> wrote:

> I tried to enable the custom CSS on the admin area and it broke a lot of
> things. After that, I set the styles you want as default, but it still
> looks bad.
>
> [image: screenshot from 2016-05-16 21-22-58]
> <https://cloud.githubusercontent.com/assets/1631275/15307829/4c5ef1a8-1bad-11e6-9ac3-22c67bac4e93.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/opennorth/citizenbudgetapp.com/issues/125#issuecomment-219588066>
>



-- 
*​*

*If you're at the GFOA in Toronto come by ​the Exhibit Hall ​and say hi
to ​us at booth #508! *

*Laurence Harvey Leclerc*
Product Development Manager
Open North / Citizen Budget
1.888.750.4980 x. 706

Visit our NEW website - http://citizenbudget.com
@opennorth

**Comment by cmonagle** [comment] 2017-02-14 10:09
Duplicate of https://github.com/opennorth/citizenbudgetapp.com/issues/140

**Closed by cmonagle** 2017-02-14 10:09 UTC
Labels: bug, frontend
